name: flutter_madkd
description: Flutter Mobile App Development keuzedeel project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  units_converter: ^2.1.1
  dropdown_search: ^5.0.6
  intl: ^0.18.1
  responsive_grid_list: ^1.4.0
  firebase_database: ^10.3.3
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - images/coffee.png
  - images/coffeebackground.png